version: '3'

services:
  database:
    container_name: student_mysql
    image: mysql
    environment:
      MYSQL_DATABASE: student
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: su
      MYSQL_PASSWORD: admin

  student_service:
    build: .
    container_name: student_ms
    image: student_image
    depends_on:
      - database
    environment:
      DATABASE_HOST: database
      DATABASE_USER: su
      DATABASE_PASSWORD: admin
#    restart: always
      entrypoint: /bin/sh
    command: >
      -c "
      while ! (nc -z student_mysql 3306); do sleep 1; echo 'Waiting for database to up...'; done;
      echo 'Database is up'
      echo 'Starting Student Service...' &&
      java -jar student.jar
      "
    ports:
      - 2018:2018
