version: '3'

services:
  database:
    container_name: student_mysql
    image: mysql
    environment:
      MYSQL_DATABASE: student
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: su
      MYSQL_PASSWORD: admin
    ports:
      - 3306:3306

  student_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: student_ms
    image: student_image
    depends_on:
      - database
    environment:
      DATABASE_HOST: database
      DATABASE_USER: su
      DATABASE_PASSWORD: admin
    ports:
      - 2018:2018